### ISSUE TITLE
About Data publishing (MF-API)

### ISSUE THREAD

**Issue by ogi-ts-shimizu** [aistairc/pygeoapi-mf-api#2]
I have a question about modifying the documentation. 
Could you please provide details on the specific items and the content that 
should be written in the code block for the Data publishing Provider? 
For example, **Maps** lists two items: **MapScript** and **WMSFacade.** 
We created a new file, **“postgresql_mobilitydb.py”**, in the Provider folder. 
For the MF-API, I thought it would be correct to list **MobilityDB, PyMEOS, and PostgreSQL**.
Is that correct?

I think the code block example to be something like this:
```
  providers:
      - type: feature
        name: PostgreSQL
        data:
            host: 127.0.0.1
            port: 5432 
            db: mobilitydb
            user: docker
            password: docker

        table: collection,mfeature,tgeometry,tproperties
```

**Describe the solution you'd like**
- Could you tell me the items to be listed for Data publishing?

- Where should I refer to for the content of the provider in the code block?

**Additional context**
- Regarding the code block, the providers for other APIs (e.g., maps) were written in the “pygeoapi-config.yml” file.
![issue1](https://github.com/user-attachments/assets/8dc23456-8875-4884-b12b-2731be3a832e)
![issue2](https://github.com/user-attachments/assets/8c06028d-8b00-431c-8676-f0ff9d105547)
